# Generated by Django 4.1.3 on 2023-04-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0003_alter_shouhin_irai_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouhin',
            name='irai_num',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='依頼No'),
        ),
    ]
