# Generated by Django 4.1.3 on 2023-04-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0007_alter_shouhin_irai_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='irai_num_rental',
            field=models.CharField(max_length=10, verbose_name='依頼No'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='nouhin_day',
            field=models.DateField(blank=True, null=True, verbose_name='納品書日付'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_day',
            field=models.DateField(blank=True, null=True, verbose_name='貸出日'),
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='irai_num',
            field=models.CharField(blank=True, max_length=10, verbose_name='依頼No'),
        ),
    ]
