# Generated by Django 4.1.3 on 2023-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0009_alter_rental_nouhin_day_alter_rental_rental_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='irai_num_rental',
            field=models.IntegerField(verbose_name='依頼No'),
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='irai_num',
            field=models.IntegerField(default=0, verbose_name='依頼No'),
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='joutai',
            field=models.IntegerField(default=0, verbose_name='状態'),
        ),
    ]
