# Generated by Django 4.1.3 on 2023-04-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0010_alter_rental_irai_num_rental_alter_shouhin_irai_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_num', models.IntegerField(verbose_name='順番')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='サイズ')),
            ],
        ),
    ]
