# Generated by Django 4.1.3 on 2023-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0011_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_test',
            field=models.CharField(blank=True, max_length=30, verbose_name='サイズ'),
        ),
    ]
