# Generated by Django 4.1.3 on 2023-04-20 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0013_remove_size_size_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouhin',
            name='size_num',
            field=models.IntegerField(default=0, verbose_name='サイズ値'),
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='touroku_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日'),
            preserve_default=False,
        ),
    ]
