# Generated by Django 4.1.3 on 2023-04-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0015_shozoku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shozoku',
        ),
    ]
