# Generated by Django 4.1.3 on 2023-04-24 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0023_rireki_rental_password_rireki_rental_rental_maxday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='貸出日'),
            preserve_default=False,
        ),
    ]
