# Generated by Django 4.1.3 on 2023-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0025_rireki_rental_unsou_com_rireki_rental_unsou_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rireki_rental',
            name='unsou_com',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='運送会社'),
        ),
        migrations.AlterField(
            model_name='rireki_rental',
            name='unsou_num',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='問い合わせ番号'),
        ),
    ]
