# Generated by Django 4.1.3 on 2023-05-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0027_auto_20230427_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='rireki_shouhin',
            name='irai_hontai_kubun',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='区分'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rireki_rental',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rireki_shouhin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shozoku',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
