# Generated by Django 4.1.3 on 2023-05-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0028_rireki_shouhin_irai_hontai_kubun_alter_rental_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rireki_rental',
            name='haisou_adress',
        ),
        migrations.AddField(
            model_name='rireki_rental',
            name='haisou_banchi',
            field=models.CharField(blank=True, max_length=30, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='rireki_rental',
            name='haisou_build',
            field=models.CharField(blank=True, max_length=30, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='rireki_rental',
            name='haisou_city',
            field=models.CharField(blank=True, max_length=30, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='rireki_rental',
            name='haisou_pref',
            field=models.CharField(blank=True, max_length=10, verbose_name='都道府県'),
        ),
    ]
