# Generated by Django 4.1.3 on 2023-05-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0029_remove_rireki_rental_haisou_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_num', models.IntegerField(verbose_name='順番')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='サイズ')),
            ],
        ),
    ]
