# Generated by Django 4.1.3 on 2023-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0030_size_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='rireki_rental',
            name='cancel_day',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='キャンセル日'),
        ),
        migrations.AddField(
            model_name='rireki_rental',
            name='cancel_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='キャンセル担当'),
        ),
    ]
