# Generated by Django 4.1.3 on 2023-05-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0031_rireki_rental_cancel_day_rireki_rental_cancel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size_test',
        ),
    ]
