# Generated by Django 4.1.3 on 2023-05-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0032_delete_size_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_num', models.IntegerField(verbose_name='順番')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='カテゴリ')),
                ('category_ex', models.CharField(blank=True, max_length=100, verbose_name='説明')),
            ],
        ),
        migrations.AlterField(
            model_name='shouhin',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='カテゴリ'),
        ),
    ]
