# Generated by Django 4.2.1 on 2023-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0034_shouhin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_num', models.CharField(max_length=20, verbose_name='サンプルNo')),
                ('shouhin_num', models.CharField(max_length=20, verbose_name='商品番号')),
                ('shouhin_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('color', models.CharField(max_length=255, verbose_name='カラー')),
                ('size', models.CharField(max_length=20, verbose_name='サイズ')),
            ],
        ),
    ]
