# Generated by Django 4.2.1 on 2023-06-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0038_rireki_rental_haisou_delitime_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rireki_rental',
            name='rental_day',
            field=models.DateTimeField(auto_now_add=True, verbose_name='依頼日'),
        ),
    ]
