# Generated by Django 4.2.1 on 2023-06-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0039_alter_rireki_rental_rental_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='rireki_shouhin',
            name='henkyaku',
            field=models.IntegerField(default=0, verbose_name='状態'),
        ),
        migrations.AddField(
            model_name='rireki_shouhin',
            name='henkyaku_day',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='返却日'),
        ),
    ]
