# Generated by Django 4.2.1 on 2023-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0043_alter_rental_rental_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_day',
            field=models.DateField(auto_now_add=True, verbose_name='貸出日'),
        ),
    ]
